#!/bin/bash
# Lightweight script to set up the Caribbean Config
 
display_usage() { 
   echo
   echo "  Auto-Config: Caribbean"
   echo "  **********************"
   echo
   echo "  usage: ${0##*/} -w path_to_install_nemo -x path_to_intall_xios"
   echo
   echo "  flags:  -w full path to where nemo will be installed"
   echo "          -x full path to where xios will be installed"
   echo
   exit 1
	} 
# if less than two arguments supplied, display usage 
	if [  $# -le 3 ] 
	then 
		display_usage
		exit 1
	fi 
# if less than two arguments supplied, display usage 
	if [  $# -ge 5 ] 
	then 
		display_usage
		exit 1
	fi 
# check whether user had supplied -h or --help . If yes display usage 
	if [[ ( $# == "--help") ||  $# == "-h" ]] 
	then 
		display_usage
		exit 0
	fi 

while getopts w:x: option
  do
  case "${option}"
  in
  w) export WORK_DIR=${OPTARG};;
  x) export XIOS_DIR=${OPTARG};;
  esac
done

if [ ${WORK_DIR:0:1} != "/" ]; then
  echo "WORK_DIR must use full path"
  exit 1
fi

if [ ${XIOS_DIR:0:1} != "/" ]; then
  echo "XIOS_DIR must use full path"
  exit 1
fi

# Change to some working directory of choice
if [ ! -d "$WORK_DIR" ]; then
  mkdir $WORK_DIR
fi
cd $WORK_DIR

echo "Make sure that the correct modules are loaded"

module load PrgEnv-intel
module load cray-hdf5-parallel
module load cray-netcdf-hdf5parallel

# Checkout the NEMO code from the SVN Paris repository 
echo "Checking out NEMO repository"
svn co http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/trunk -r 8395 nemo
cd nemo/NEMOGCM/CONFIG

# Define the location of where the Caribbean configuration tarballs were downloaded (keep this as the work dir for now)
export DOWNLOAD_DIR="$WORK_DIR"

# Download the source and data files
echo "Downloading Caribbean release v1.0"

wget -P $DOWNLOAD_DIR https://github.com/NOC-MSM/Caribbean/releases/download/v1.0/caribbean_netcdf_files.tar.gz
wget -P $DOWNLOAD_DIR https://github.com/NOC-MSM/Caribbean/archive/v1.0.tar.gz

# copy configuration and its source code mods into correct locations before compilation
pushd $DOWNLOAD_DIR; tar xvfz v1.0.tar.gz; popd
cp -a $DOWNLOAD_DIR/Caribbean-v1.0 $WORK_DIR/nemo/NEMOGCM/CONFIG/Caribbean
echo $WORK_DIR
echo $DOWNLOAD_DIR

# Add it to the configuration list
echo "Caribbean OPA_SRC" >> cfg.txt

echo $XIOS_DIR
# Choose an appropriate directory for your XIOS installation
if [ ! -d "$XIOS_DIR" ]; then
  mkdir $XIOS_DIR
fi
cd $XIOS_DIR
echo $PWD
echo "Checking out xios repository"
svn co http://forge.ipsl.jussieu.fr/ioserver/svn/XIOS/trunk@1242 xios
cd xios
cp $WORK_DIR/nemo/NEMOGCM/CONFIG/Caribbean/arch_xios/* ./arch
echo "Compiling xios"
./make_xios --full --prod --arch XC30_ARCHER --netcdf_lib netcdf4_par --job 4

# Let's update the path to xios
export XIOS_DIR=$XIOS_DIR/xios

cd $WORK_DIR/nemo/NEMOGCM/CONFIG/Caribbean
cp ARCH/* ../../ARCH

echo "Compiling nemo Caribbean Config"
cd ../
./makenemo -n Caribbean -m XC_ARCHER_Intel -j 4

cd Caribbean/EXP00
echo "Gathering forcing data"
tar xvfz $DOWNLOAD_DIR/caribbean_netcdf_files.tar.gz

ln -s $XIOS_DIR/bin/xios_server.exe xios_server.exe
echo
echo "  Auto-Config: Caribbean"
echo "  **********************"
echo
echo "  To run the Caribbean Configuration:"
echo
echo "  - to generate additional ERA5 forcing data "
echo "      see $WORK_DIR/nemo/NEMOGCM/CONFIG/Caribbean/SCRIPTS/ERA5-Forcing.md"
echo "      for more details" 
echo
echo "  - update the runscript.pbs accordingly "
echo "      (project code, nodes, modules, etc)"
echo
echo "  - submit via the qsub command"
echo    
